### ISSUE TITLE
Feedback from testers

### ISSUE THREAD

**Issue by trubb** [olandr/dh-project#62]
The following feedback has been received from testers
- [x] Unclear what credentials / formats are required when signing up ~ pr #63
- [x] Character selection screen is to clustered, can you present them side by side instead ~ pr #68 
- [x] In the area it looks like I'm fighting myself ~ pr #60
- [x] The leaderboard seems to not count my character ~(ping #61; still not showing XP)
- [x] There should be caps on the stats ~ pr #72
- [x] Use the same font everywhere ~ issue #35 ~ pr #66
- [x] Consider how the buttons are sized everywhere, and how they are styled (css reset?), put some radius on them? ~ issue #35 pr #80
- [x] The background color is flesh-colored and not very nice ~ pr #80
- [x] Logout button ~ pr #79 
- [x] No healthbar in summary screen ~ pr #83
- [x] Move views into one directory and presenters into another ~ pr #81 
- [x] Put user feedback into own directory and collate it into markdown files.

**Comment by trubb** [comment]
PR #63 solves the first issue of credential rules being unclear.

**Comment by trubb** [comment]
PR #68 solves the issue of the character selection screen being a bit too clustered.

**Comment by trubb** [comment]
All things mentioned here resolved
